"""Add routing_reason to Message

Revision ID: 7774cccd5fc2
Revises: 68f9e29251e4
Create Date: 2026-06-08 19:14:32.187412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7774cccd5fc2'
down_revision: Union[str, Sequence[str], None] = '68f9e29251e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('routing_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'routing_reason')
    # ### end Alembic commands ###
